name: $pluginName
main: $pluginMain
depend: [ Kotlin, ProtocolLib ]
api-version: '1.17'
version: $version
commands:
  potato:
    description: Commands related to the spring potato plugin.
    usage: /potato